command_timeout = 300000

[nodejs]
format = '[js: $version ](bold green)'

[aws]
format = '[AWS: ($profile )($region )](bold-blue)'

[git_branch]
format = '[Branch: ($branch )](red)'

[line_break]
disabled = false

[time]
time_format = "%T"
format = " $time($style) "
style = "bright-white"
disabled = false
